### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by lyhistory** [lyhistory/Peter-s-Tool#2]
@farrahfazirah for the discussion, I copy over some of the comments here

**Comment by lyhistory** [comment]
![latest](https://user-images.githubusercontent.com/1522513/44161200-31ec5580-a0ef-11e8-8423-2f41f3c9901e.png)
please have a review to confirm whether this version meet the functional requirement, I know there are a lot work to do to improve the look and feel, for example:
1)reset the ticket list to empty
2)too painful to scroll down 100 dropdownlist to find the desired location, need to customize the combobox to add a search filter.
3) the datetime picker is too basic, not ease to use
4) for rendering datepicker ui component based on the XML, for now I check the id against hardcoded 'time' to decide whether to render it as a Jtextfied or a datetimepicker, this will cause issue when the xml variant with differenet id or multiple datetime attributes
etc

**Comment by lyhistory** [comment]
![2](https://user-images.githubusercontent.com/1522513/44161248-534d4180-a0ef-11e8-801d-a75ae7988af6.png)
1. I have added in a "RESET" button as a suggestion beside the ticket list field
2. I have a question regarding this:
- Is each individual Token ID a dropdown? I'm thinking that you could do something like this https://codepen.io/kaleem78/pen/YjLqXQ where all the Token IDs are in one dropdown field and you could input text on the dropdown field to search for a particular Token ID.
- However, in my UI, in case you still want to add in a search field, I have added in a UI suggestion.
3. I did not add this in the UI above: Can we have a DATE and TIME attribute? There is only TIME attribute. I believe we should add in a DATE attribute to make the date time picker easy to use.

**Comment by lyhistory** [comment]
@farrahfazirah sorry for my limited English statements, not a native speaker, let me try to make some clarification:
first of all, please make sure you get the latest code from branch **feature/desktop-magiclink**
from your screenshot I think the your code is not synced the latest, the time field on the upper pane supposed to be a datetime picker.

1. the reset button looks fine 
2.
1)each token id is a dropdown, yes, if I'm not mistaking the requirement, when you generate the "Magic Link", it supposed to be a N:1 mapping, means a list of tokenID generates one Magic Link (as showing in my screenshot above)
2) I don't think we need a 'search box' for the tokenid,  I'm talking about the the location(country/city) dropdownlist, and the 'search field' effect I'm thinking of is exactly the same with the one you suggest https://codepen.io/kaleem78/pen/YjLqXQ

3. this date picker I'll try to enhance it first, I don't think we need two separate attributes, 
please note that there are two datetimepicker: Time attributes on upper pane, and expireTime on lower pane, one more reason I don't want to separate date and time is I have to add listener to the datetimePicker, it will be more complicated if separate them

**Comment by farrahfazirah** [comment]
I have spoken to Weiwu regarding the UI issue. The current UI has to be scrapped.

The new UI proposed is below:

![contractmanager](https://user-images.githubusercontent.com/20555752/44201841-d9fc3000-a17c-11e8-9487-46befd8c9c52.png)
![contractmanager2](https://user-images.githubusercontent.com/20555752/44201863-e7b1b580-a17c-11e8-9c11-2746c8c02013.png)
![contractmanager3](https://user-images.githubusercontent.com/20555752/44201892-fdbf7600-a17c-11e8-96cf-2c5c5104167e.png)

**Comment by lyhistory** [comment]
some questions:
1. are we going to use JSWING GUI or Web UI, have you discussed it? 
and I found some embedded webkit library which enable us to use HTML+CSS with JSwing, but unfortunate, some are not free, for example: https://www.teamdev.com/jxbrowser#licensing-pricing
samples: https://dzone.com/articles/htmlcssjavascript-gui-java-0

2. can you give me a complete flow with the new UI, because from this three screenshots I feel confused:
1) missing Panel for the xml attributes (the upper panel from my screenshot)
2) what does the tabs represent?
3) create new xml ? does it mean the same as upload xml?
4) missing connection: tokenID generation and magic link generation 
5) the owner column, from the requirement, I don't see owner information in the magic link, not sure why we need owner here, information of magicLink:
MagicLink: https://app.awallet.io/base64(Message|Signature)
priceInWei		32 bytes (4 bytes MicroEth)
expiry			32 bytes (4 bytes unsigned)
contractAddress 20 bytes 
tokenIDs		32bytes * count

6) from the UI I don't know which are textfield , which are dropdown,

could you please provide the new design by making static html pages with dummy data?

**Comment by miang719** [comment]
@farrahfazirah take a look

**Comment by colourful-land** [comment]
This is closed as we fixed the direction
