### ISSUE TITLE
track magic link redeem status - both spawnable and traditional transfer/sales links

### ISSUE THREAD

**Issue by colourful-land** [lyhistory/Peter-s-Tool#7]
stage 3: update UI of the tool by checking magic link redeem status through web3j

**Comment by lyhistory** [comment]
still working in progress, last weekends got issues with my truffle solc, and Ganache private chain,
I used to test solidity with web3js+truffle+Ganache for local dev env, 
but with web3j got TxHashMissmatch issue when make transaction, 
then I wasted some time debugging into web3j library, but only found that the remoteHash returned from sending rawTransaction not equals to localHash, and I found someone also has similar wired issue with Ganache,
resolved after upgrade to latest though

**Comment by lyhistory** [comment]
I raised an issue in the contract https://github.com/AlphaWallet/contracts/issues/74
I was stuck in several problems about the Spawnable Meetup contract when I try to redeem and verify the token, finally I make it through by modified the contract, so now I can continue to work on the UI display

**Comment by lyhistory** [comment]
done the functionality, robustness and details still need to be enhanced

**Comment by lyhistory** [comment]
added some user friendly warning:
1. all good state
![magiclinktool1](https://user-images.githubusercontent.com/1522513/51330459-8470da00-1ab2-11e9-8c63-f7f4224805de.png)
2. disconnected state
![magiclinktool2](https://user-images.githubusercontent.com/1522513/51330538-b5e9a580-1ab2-11e9-98a9-520dc3d8deef.png)

3. wrong private key state
![magiclinktool3](https://user-images.githubusercontent.com/1522513/51330547-b8e49600-1ab2-11e9-928e-9aef9d840835.png)
